env:
  browser: true
  es2021: true
extends:
  - next/core-web-vitals
  - next/typescript
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
rules:
  {
    'prettier/prettier': 'error',
    'react/react-in-jsx-scope': 'off',
    'react/no-children-prop': 'off',
    '@typescript-eslint/no-non-null-assertion': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/no-empty-function': 'off',
    '@typescript-eslint/no-unused-vars': 'warn',
    'react/no-unknown-property': 'off',
    '@next/next/no-html-link-for-pages': ['error', 'packages/'],
  }
settings:
  react:
    version: detect
